using Bybit.Net.Enums;
using System.Text.Json.Serialization;
using System;

namespace Bybit.Net.Objects.Models.V5
{
    /// <summary>
    /// Transaction info
    /// </summary>
    [SerializationModel]
    public record BybitTransactionLog
    {
        /// <summary>
        /// ["<c>id</c>"] Unique id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; } = string.Empty;
        /// <summary>
        /// ["<c>symbol</c>"] Symbol
        /// </summary>
        [JsonPropertyName("symbol")]
        public string Symbol { get; set; } = string.Empty;
        /// <summary>
        /// ["<c>category</c>"] Product
        /// </summary>

        [JsonPropertyName("category")]
        public Category Category { get; set; }
        /// <summary>
        /// ["<c>side</c>"] Side
        /// </summary>

        [JsonPropertyName("side")]
        public PositionSide Side { get; set; }
        /// <summary>
        /// ["<c>transactionTime</c>"] Transaction time
        /// </summary>
        [JsonConverter(typeof(DateTimeConverter))]
        [JsonPropertyName("transactionTime")]
        public DateTime TransactionTime { get; set; }
        /// <summary>
        /// ["<c>type</c>"] Type
        /// </summary>
        [JsonPropertyName("type")]
        public TransactionLogType Type { get; set; }
        /// <summary>
        /// ["<c>transSubType</c>"] Transaction sub-type, movePosition, used for the logs generated by move position. "" by default
        /// </summary>
        [JsonPropertyName("transSubType")]
        public string SubType { get; set; } = string.Empty;
        /// <summary>
        /// ["<c>qty</c>"] Quantity
        /// </summary>
        [JsonPropertyName("qty")]
        public decimal? Quantity { get; set; }
        /// <summary>
        /// ["<c>size</c>"] Size
        /// </summary>
        [JsonPropertyName("size")]
        public decimal? Size { get; set; }
        /// <summary>
        /// ["<c>currency</c>"] Asset
        /// </summary>
        [JsonPropertyName("currency")]
        public string Asset { get; set; } = string.Empty;
        /// <summary>
        /// ["<c>tradePrice</c>"] Trade price
        /// </summary>
        [JsonPropertyName("tradePrice")]
        public decimal? TradePrice { get; set; }
        /// <summary>
        /// ["<c>funding</c>"] Funding fee
        /// </summary>
        [JsonPropertyName("funding")]
        public decimal? Funding { get; set; }
        /// <summary>
        /// ["<c>fee</c>"] Trading fee
        /// </summary>
        [JsonPropertyName("fee")]
        public decimal? Fee { get; set; }
        /// <summary>
        /// ["<c>cashFlow</c>"] Cash flow
        /// </summary>
        [JsonPropertyName("cashFlow")]
        public decimal? Cashflow { get; set; }
        /// <summary>
        /// ["<c>change</c>"] Change
        /// </summary>
        [JsonPropertyName("change")]
        public decimal? Change { get; set; }
        /// <summary>
        /// ["<c>cashBalance</c>"] Cash balance
        /// </summary>
        [JsonPropertyName("cashBalance")]
        public decimal? CashBalance { get; set; }
        /// <summary>
        /// ["<c>feeRate</c>"] Fee rate
        /// </summary>
        [JsonPropertyName("feeRate")]
        public decimal? FeeRate { get; set; }
        /// <summary>
        /// ["<c>bonusChange</c>"] Bonus change
        /// </summary>
        [JsonPropertyName("bonusChange")]
        public decimal? BonusChange { get; set; }
        /// <summary>
        /// ["<c>tradeId</c>"] Trade id
        /// </summary>
        [JsonPropertyName("tradeId")]
        public string? TradeId { get; set; }
        /// <summary>
        /// ["<c>orderId</c>"] Order id
        /// </summary>
        [JsonPropertyName("orderId")]
        public string? OrderId { get; set; }
        /// <summary>
        /// ["<c>orderLinkId</c>"] Client order id
        /// </summary>
        [JsonPropertyName("orderLinkId")]
        public string? ClientOrderId { get; set; }
        /// <summary>
        /// ["<c>displayType</c>"] Display type
        /// </summary>
        [JsonPropertyName("displayType")]
        public string? DisplayType { get; set; }
    }
}
