using CryptoExchange.Net.Authentication;
using System;
using System.Linq;

namespace Bybit.Net
{
    /// <summary>
    /// Bybit credentials
    /// </summary>
    public class BybitCredentials : ApiCredentials
    {
        /// <summary>
        /// Provided credential type
        /// </summary>
        public ApiCredentialsType CredentialType => CredentialPairs.First().CredentialType;

        /// <summary>
        /// </summary>
        [Obsolete("Parameterless constructor is only for deserialization purposes and should not be used directly. Use parameterized constructor instead.")]
        public BybitCredentials() { }

        /// <summary>
        /// Create API credentials using an API key and secret generated by the server. This assumes HMAC authentication. If you want to use RSA authentication, use the appropriate constructor or static method instead.
        /// </summary>
        /// <param name="apiKey">API key</param>
        /// <param name="secret">API secret</param>
        public BybitCredentials(string apiKey, string secret) : this(new HMACCredential(apiKey, secret)) { }

        /// <summary>
        /// Create Bybit credentials using HMAC credentials
        /// </summary>
        /// <param name="credential">The HMAC credentials</param>
        public BybitCredentials(HMACCredential credential) : base(credential) { }

#if NETSTANDARD2_1_OR_GREATER || NET7_0_OR_GREATER
        /// <summary>
        /// Create Bybit credentials using RSA credentials in PEM format
        /// </summary>
        /// <param name="rsaCredential">RSA credentials</param>
        public BybitCredentials(RSAPemCredential rsaCredential)
            : base(rsaCredential)
        {
        }
#endif
        /// <summary>
        /// Create Bybit credentials using RSA credentials in XML format
        /// </summary>
        /// <param name="rsaCredential">RSA credentials</param>
        public BybitCredentials(RSAXmlCredential rsaCredential)
            : base(rsaCredential)
        {
        }

        /// <inheritdoc />
#pragma warning disable CS0618 // Type or member is obsolete
        public override ApiCredentials Copy() => new BybitCredentials { CredentialPairs = CredentialPairs };
#pragma warning restore CS0618 // Type or member is obsolete
    }
}
